### ISSUE TITLE
Custom wildcard certificate for openshift router addon

### ISSUE THREAD

**Issue by jperville** [IshentRas/cookbook-openshift3#103]
I need to deploy a new production environment, where the applications are served by the router using a non self-signed wildcard certificate (eg. `*.cloudapps.domain.com`).

The `oc adm router` command accepts a `-default-cert` option which works like this:
```sh
  --default-cert='': Optional path to a certificate file that be used as the default certificate.
 The file should contain the cert, key, and any CA certs necessary for the router to serve the certificate.
```

@ianmiell @IshentRas do you have some ideas on how to implement the feature in an upcoming PR?
 - should we use data bag (with flexible name) to store the certificate
 - should we make this cookbook depend on the [certificate cookbook](https://github.com/atomic-penguin/cookbook-certificate/)
 - how can we expose the openshift console on port 443 (instead of port 8443) using the proper certificate?
 - how to redeploy the router component if the certificate is updated in the databag?

**Comment by jperville** [comment]
This article might be useful: http://guifreelife.com/blog/2016/03/24/Replace-OpenShift-Console-SSL-Certificate

**Comment by IshentRas** [comment]
For the console, I am confused as we have already got that capability
https://github.com/IshentRas/cookbook-openshift3/blob/master/templates/default/master.yaml.erb#L191-L201

**Comment by jperville** [comment]
Thanks @IshentRas , it looks like the named certificates feature will work for the console. I'm still looking for advice on how to implement a way to pass the default-cert option when deploying the router. I will start working on a PR today, but all advice welcome.

**Comment by jperville** [comment]
Hi @IshentRas  I managed to deploy the openshift console using real wildcard certificate (not worked yet on deploying the router default certificate), however I have a couple PRs to submit as a consequence.

**Comment by jperville** [comment]
Regarding the feature of deploying the router with a default cert, it seems that pre-populating a secret named "router-certs" in the default namespace with entries named `tls.key` and `tls.cert` does the trick.

My proposal for a future PR: add the following attributes:
 - `node['cookbook-openshift3']['openshift_hosted_router_certificate'] = '/path/to/cert.pem'`
 - `node['cookbook-openshift3']['openshift_hosted_router_key'] = '/path/to/key.pem'`

These attributes would be passed to the openshift_deploy_router LWRP, which would encode the certificate and key in the expected secret prior to running `oc adm router`. Of course, if the attributes are not set then no secret is created and the router will be deployed to use generated certificates.

This would be minimally intrusive and would leave me a chance in my wrapper cookbook to inject the key and certificate (and probably reuse the certificate I configured for the public access to the console).

Please let me know what you think before I start implementing.

**Comment by jperville** [comment]
Closing this issue since my PR #109 got merged.
