### ISSUE TITLE
RFC: dummy recipes for node assignment

### ISSUE THREAD

**Issue by ianmiell** [IshentRas/cookbook-openshift3#117]
Here at $CORP we have two environments:

- on premise
- a Major Cloud Provider (MCP)

When on premise we provision servers and get an IP and a node hostname, which works great with this cookbook (in fact, it was why the cookbook was written this way). Changing the run list for a node requires a change request, which is why we went with this approach.

Now on the MCP, we are in the reverse situation: we can specify the run list in terraform, but don't know the IP and node hostname!

So I suggest the following:

- where we currently have lines like:

```
if node_servers.find { |server_node| server_node['fqdn'] == node['fqdn'] }
```

instead we might have:

```
if node_servers.find { |server_node| server_node['fqdn'] == node['fqdn'] } || node.recipe?('cookbook-openshift3::is_node')
```

(above is pseudo-code, I've not tested yet).

- I rejected using node.role?(name) because there may be name clash, whereas we can namespace a recipe assignment in the runlist

Would anyone object to such a change?

**Comment by ianmiell** [comment]
Note: the first master / first etcd setting would have to remain in a role/environment variable. There is no way in a run list to specify such a setting afaict.

This is 'ok' from our point of view, as the first master and first etcd node can be relatively static within an infrastructure, ie requires only one CR.

**Comment by ianmiell** [comment]
OK, the previous entry was not accurate: we want _no_ CRs.

So this is a proposal:

- if a file is configured in the cookbook (eg /etc/origin/chef-data.json), expect a file to be there that describes the place to get the master certificates (the 'first' master) and the etcd certificates (the 'first' etcd host)
- the file should be in json format

Questions outstanding: can we have a separate place to get the certs from? why do we need a separate location to get the etcd certs from?

**Comment by ianmiell** [comment]
@jperville @IshentRas am planning on pushing this over the weekend.

**Comment by jperville** [comment]
@ianmiell I quite busy this week but I will be watching and playing with your changes. And of course I will report and/or fix any issue I encounter.

**Comment by IshentRas** [comment]
@ianmiell Lets's have a talk about it :-) I am quite keen to understand it

**Comment by ianmiell** [comment]
When can we talk Will? It's quite an interesting requirement, and I had to draw it out to explain it to everyone at work :) It might also make testing simpler :)
I'm doing work on the branch 'runlist'.
BTW, the Jenkins tests now cover all branches (Jenkins multibranch).

**Comment by ianmiell** [comment]
Discussed with Will today:

- Given a clustername (eg 'team1') 
- We can have dynamic role assignment that's queried with the chef server
- Roles can be eg: 'node_team1', 'master_team1'
- Certificates will be replicated across nodes
- Where to get the certs from? Search for nodes with the appropriate role assigned on the chef server, and pick the oldest one
- Which one is the oldest? The first in the list (are roles removed on destruction? see below). We think the list retains order. 

Outstanding questions:

- Can we get tags from knife? And/or ohai/168.254.168.254?
- Can we get info into 168.254...  that could be picked up by chef
- Can tags be updated dynamically by TF here?
- Is there a creation time tag by default in AZN
- Do we remove role assignments from nodes?
- Does run list get reflected on chef server (ie can we search for them?)

**Comment by ianmiell** [comment]
According to team here, destruction results in removal of role assignment from server.

**Comment by ianmiell** [comment]
@IshentRas I'd like to pick this up again. It's quite important for our test automation piece.
The other certificate_server branch changes should make some of this easier to achieve, I think.

**Comment by IshentRas** [comment]
@ianmiell Is this still relevant or can be closed?

**Comment by ianmiell** [comment]
Can be closed, we did it!
