### ISSUE TITLE
ose versions in tests being respected

### ISSUE THREAD

**Issue by ianmiell** [IshentRas/cookbook-openshift3#135]
While looking into an upgrade issue here I fired up a test with this environment:

```
{
  "name": "ocp-cluster-environment",
  "description": "",
  "cookbook_versions": {},
  "json_class": "Chef::Environment",
  "chef_type": "environment",
  "default_attributes": {},
  "override_attributes": {
    "cookbook-openshift3": {
      "deploy_dnsmasq": true,
      "ose_major_version": "1.4",
      "master_servers": [
        {
          "fqdn": "master1.vagrant.test",
          "ipaddress": "172.28.128.45"
        }
      ],
      "node_servers": [
        {
          "fqdn": "node1.vagrant.test",
          "ipaddress": "172.28.128.46",
          "labels": "region=infra"
        },
        {
          "fqdn": "node2.vagrant.test",
          "ipaddress": "172.28.128.47",
          "labels": "region=user"
        }
      ],
      "openshift_deployment_type": "origin",
      "openshift_hosted_managed_router": false,
      "openshift_hosted_managed_registry": false
    }
  }
}
```

and although 1.4 is set, 1.5 is installed.

It may be that these tests are misconfigured - either way I need to determine as it may be that, and/or docs. 

Am running more tests, and plan to add a test to check the version is what we expect.

**Comment by ianmiell** [comment]
Setting the ose_version in environment.json triggers a version error when re-running chef.

**Comment by jperville** [comment]
You have to specify both ose_version and ose_major version. If ose_version is not set, then the latest packages from centos paas repository is installed, which is v1.5.0.

See https://github.com/IshentRas/cookbook-openshift3/blob/master/test/roles/openshift3-base-ose14.json for example role which setups OSE 1.4.x environment.

**Comment by ianmiell** [comment]
The multi_node_separate_etcd _does_ have it set:

```
      "ose_major_version": "{{ cfg['ose_major_version'] }}",                                                                                                                               
      "ose_version": "{{ cfg['ose_version'] }}",            
```

so this is a problem just with the environment.json in the quick test.
