### ISSUE TITLE
iptables error on kitchen converge

### ISSUE THREAD

**Issue by xxwassyxx** [IshentRas/cookbook-openshift3#149]
So i realize this is really an issue with iptables, however the reference is to what is going in in this cookbook.
It looks like we are referencing a template called firewall_jump_rule.erb which only has one line 
`-A INPUT -j OS_FIREWALL_ALLOW`
Then with the iptables cookbook that calls iptables-rebuild. The error tho seems to be what actually creates the chain "OS_FIREWALL_ALLOW"? Is this meant to be created first? Am I missing something that it isnt.

If I add creation of the chain to that file I get a different error saying it already exists. I really am not he best on iptables so I realise its soemthing simple I just dont see. Searching the googles has shown me how to create the chain, and I can but im still not certain how to make it work with the cookbooks.

the error I get is

`STDERR: iptables-restore v1.4.21: Couldn't load target `OS_FIREWALL_ALLOW':No such file or directory`

Again this is only when I kitchen converge nothing else
Let me know if you need other info

**Comment by xxwassyxx** [comment]
sweet just figured it out. I was close multiple times, but after looking at the rebuild script realizing its just ruby made this change.
```
:OS_FIREWALL_ALLOW
-A INPUT -j OS_FIREWALL_ALLOW
```
Which seems to be converging and working

**Comment by ianmiell** [comment]
How do I repro this error eg with a vm?

**Comment by ianmiell** [comment]
Ok!
