### ISSUE TITLE
Unable to provision an environment with a single master and nodes+n

### ISSUE THREAD

**Issue by sds89ufdg** [IshentRas/cookbook-openshift3#16]
I'm trying to create a cluster with:

master x 1
nodes x 2

But there is a sanity check to on the etcd script prevent this, can a config flag be provided to allow a single master?

see:

etcd_cluster.rb
line 91

**Comment by sds89ufdg** [comment]
ok, we've tried a couple of different role configurations, set openshift_HA as false, listed a single master, with no peers, listed all three nodes as nodes and etcd members. But it fails to run on the master due to an issue with the master_standalone.rb.

Is there a way to get a cluster ( actually I need two ) running as:

master x 1 
nodes x 2

We're trying to build this as the original cluster:
master x 3
nodes x 2

wouldn't init any PODs, router registry etc. Even though we could run containers locally via docker.

**Comment by IshentRas** [comment]
Hi,

You cannot do openshift_HA with only a master ...

So which one are you trying to do? 
a) master x1 ; nodes x2
b) master x3 ; nodes x2

master_standalone.rb is only played when openshift_HA = false (Which is the default)
Can you post your attributes? I'll help you to getting started.

**Comment by sds89ufdg** [comment]
Hi,

Trying option A at the moment:

`{
  "name": "is-apaaseng-osev3-b-openshift3_enterprise-osev3-etf-poc02",
  "description": "Role for ETF PoC02 Cluster",
  "json_class": "Chef::Role",
  "default_attributes": {},
  "override_attributes": {
    "cookbook-openshift3": {
      "openshift_HA": false,
      "openshift_master_cluster_vip": "10.123.53.128",
      "openshift_cluster_name": "console.poc02.cluster.openshift.etf.barcapetf.com",
      "master_servers": [
        {
                "fqdn":"ldtdsr001005377.etf.barcapetf.com",
                "ipaddress":"10.123.52.149"
        }
      ],
      "etcd_servers": [
        {
                "fqdn":"ldtdsr001005377.etf.barcapetf.com",
                "ipaddress":"10.123.52.149"
        },
        {
                "fqdn":"ldtdsr001005368.etf.barcapetf.com",
                "ipaddress":"10.123.52.123"
        },
        {
                "fqdn":"ldtdsr001005367.etf.barcapetf.com",
                "ipaddress":"10.123.52.121"
        }
      ],
      "master_peers": [
      ],
      "node_servers": [
        {
                "fqdn":"ldtdsr001005377.etf.barcapetf.com",
                "ipaddress":"10.123.52.149"
        },

        {
                "fqdn":"ldtdsr001005367.etf.barcapetf.com",
                "ipaddress":"10.123.52.121"
        },
        {
                "fqdn":"ldtdsr001005368.etf.barcapetf.com",
                "ipaddress":"10.123.52.123"
        }],
      "openshift_master_router_subdomain": "poc02.openshift.etf.barcapetf.com",
      "openshift_common_public_hostname": "console.poc02.cluster.openshift.etf.barcapetf.com"
    }
  },
  "chef_type": "role",
  "run_list": [
        "role[is-apaaseng-osev3-b-openshift3_enterprise-osev3-etf-poc02]"
        ],
  "env_run_lists": {

  }
}
`

**Comment by IshentRas** [comment]
@sds89ufdg : I'll reply you in a  moment. I removed your previous post to protect the provided data (IPs..)
