### ISSUE TITLE
openshift install issue

### ISSUE THREAD

**Issue by thuynh202** [IshentRas/cookbook-openshift3#22]
Hi 

Currently I have a seven nodes setup to deploy Openshift but running into this issue. I have set up 3 master, 2 etcd, and 2 nodes. When applying the cookbook it is giving this error 

NoMethodError
-------------
undefined method `+' for nil:NilClass

62:      execute "Generate the node server certificate for #{node_server['fqdn']}" do
63:        command "#{node['cookbook-openshift3']['openshift_common_admin_binary']} ca create-server-cert --cert=server.crt --key=server.key --overwrite=true \
64>>               --hostnames=#{node_server['fqdn'] + ',' + node_server['ipaddress']} --signer-cert=#{node['cookbook-openshift3']['openshift_common_master_dir']}/master/ca.crt --signer-key=#{node['cookbook-openshift3']['openshift_common_master_dir']}/master/ca.key \
65:                --signer-serial=#{node['cookbook-openshift3']['openshift_common_master_dir']}/master/ca.serial.txt && mv server.{key,crt} /tmp/#{node_server['fqdn']}"

If this is something you can help with that would be great. Thanks.

**Comment by IshentRas** [comment]
Hi,

Sorry were pretty busy...
I have uploaded a new version v1.10.16.
Please test with this one and keep in mind that etcd cannot be a even number. Only odd (1,3,5...)

**Comment by IshentRas** [comment]
I have removed the dependency for having a odd number v.1.10.17
