### ISSUE TITLE
Redeploying certificates in non-intrusive manner

### ISSUE THREAD

**Issue by jperville** [IshentRas/cookbook-openshift3#221]
# The problem

How to regenerate and redeploy the openshift internal certificates without downtime (or at least with controlled downtime).

# Some context

Here is the validity of the cookbook-generated certificates (courtesy of `openssl x509 -in CERTIFICATE -text | grep After`):
 - openshift ca = 5 years
 - openshift master and node = 2 years
 - etcd ca and node = 1 year (!)

It has been one year since my first deployments of openshift using this cookbook.
My first etcd node certificates expired 5 days ago (fortunately service still works, until I restart etcd service at least).
I'm now trying to figure out how to regenerate those certificates without breaking the service.

 The official instructions use Ansible playbook and are found here: https://docs.openshift.com/container-platform/3.6/install_config/redeploying_certificates.html#redeploying-etcd-certificates

**Comment by IshentRas** [comment]
@jperville I originally put this simple script (long time ago...) https://github.com/IshentRas/cookbook-openshift3/blob/master/recipes/adhoc_redeploy_certificates.rb
Shall we use that as a starting point?
What is missing in it according to your needs?

@all I am more than happy to refactor it :-)

**Comment by jperville** [comment]
Hello @IshentRas , I have been playing with the adhoc_redeploy_certificates and it seems broken to me, at least in my current setup.

First run, my run list is only `recipe[cookbook-openshift3::adhoc_redeploy_certificates]`. The chef-run fails, because of file `/etc/origin/master/master-config.yml` not present. I noticed that etcd certificate was properly regenerated and the etcd service is running, however fails when trying to restart the `origin-master-api` server.

Second run, with normal run-list (`recipe[cookbook-openshift3::adhoc_redeploy_certificates]` is not present in the run-list) : the origin-master-api service restarts properly (I guess the `/etc/origin/master/master-config.yml` file has been regenerated) but the origin-node service fails because of /etc/origin/node/resolv.conf not present (I am using deploy_dnsmasq option).

Third run, same result as second run: the /etc/origin/node/resolv.conf is still not present and origin-node service does not restart.

**Comment by jperville** [comment]
I think we're losing the /etc/origin/master and /etc/origin/node files because of invocation of `tar cvfz [...] #{node['cookbook-openshift3']['openshift_node_config_dir']} [...] --remove-files` in https://github.com/IshentRas/cookbook-openshift3/blob/master/providers/openshift_redeploy_certificate.rb#L34 .

This command will archive the whole /etc/origin/node (and /etc/origin/master) directory, including the config files, where it should be tuned to only archive (and remove after archiving) the *.tgz *.pem *.crt *.kubeconfig files in those directories.

**Comment by IshentRas** [comment]
@jperville I will change the logic and align it with what offers the ansible way

**Comment by jperville** [comment]
In other words, I don't like the adhoc_redeploy_certificates recipe because it trashes the files in /etc/origin/node and /etc/origin/master which are not certificates and keys.

Also, I would like an option to regenerate the openshift certificates while keeping the generated openshift CA, which would allow to upgrade certificates in a cluster without breaking it (nodes which have not been regenerated cannot talk to nodes which have been because of `x509: certificate signed by unknown authority`).

**Comment by ianmiell** [comment]
FWIW this is similar to the investigations I did some time ago, but did not
get time to write up.

Will, this is definitely a benefit to ops, and we can make it very slick
(and also regression test!). Let's discuss on Weds.

**Comment by jperville** [comment]
Some information about renewal of expired etcd certificates: https://stackoverflow.com/questions/44529970/how-to-replace-etcd-expired-ca-cert-in-openshift-origin-cluster

I still have my production cluster with expired etcd certificates to ugprade ASAP but I don't want to risk breaking this environment, so any solution that would work (at least for etcd, no need for openshift yet) interests me.

**Comment by IshentRas** [comment]
I'll put an etcd logic tonight for you

**Comment by jperville** [comment]
Here is the manual procedure I followed to regenerate the etcd certificates that were expired on the production cluster.

Since `recipe[cookbook-openshift3::adhoc_redeploy_certificates]` was too wide-reaching (it would redeploy all certificates, and is currently broken), I tested in my VMs what would happen if I remove the certificate tarball and directories and let chef recreate them. Then I manually extracted the certificate tarballs on the relevant hosts and restarted the services in the proper order. Surprisingly, it workerd.

The procedure in details:
 1. remove the current certificate tarballs and etcd ca directory, regenerated them using chef
 2. install manually the certificates in the right place
 3. restart the affected services in the right order

I recommend these steps be practiced inside VMs before applying to real environment.

Step 1 (to do on the first master, or wherever the etcd certificates are generated by the cookbook) :

```sh
mkdir -p /root/etcd-certificate-backup
cp -a /var/www/html/etcd /var/www/html/master/generated_certs/openshift-master-* /etc/etcd/ca /root/etcd-certificate-backup
rm -rf /var/www/html/etcd /var/www/html/master/generated_certs/openshift-master-* /etc/etcd/ca -v
# then regenerate the certificates with `chef-client`
chef-client
```

Step 2: Copy the certificate tarballs to the different etcd and master nodes

In `/var/www/html/etcd/generated_certs` the cookbook generated one tarball per etcd node. Verify that the timestamp is recent to make sure that the tarballs contain the new certificates, then copy each tarball on the relevant node, then extract each tarball in the `/etc/etcd` directory, for example:
```sh
tar xvfz /var/www/html/etcd/generated_certs/etcd-master.tgz -C /etc/etcd
```

In the same manner, copy the tarballs in `/var/www/html/master/generated_certs/openshift-master-*.tgz` to the relevant master nodes. These tarballs contain the etcd certificate for the openshift master to connect to the etcd cluster. Extract each tarball in the `/etc/origin/master` directory, for example:
```sh
tar xvfz /var/www/html/master/generated_certs/openshift-master-master.tgz -C /etc/origin/master
```

Step 3: When all certificates (etcd and origin master etcd-related certificates) have been copied on every affected server, restart the services on all relevant nodes:
```sh
server origin-master-controllers stop
# wait until all instances of the origin-master-controllers stopped
service etcd restart
# wait until all etcd nodes are up using the new certificates to continue;
# on multi-node cluster, all etcd instances have to be restarted simultaneously
# check with `service etcd status` to make sure that the cluster is healthy again
service origin-master-controllers start
# wait until `service origin-master-controllers` is green
service origin-master-api restart
# wait until `service origin-master-api` is green
oc get pod --all-namespaces
# if this last command works then all is good again.
```

**Comment by IshentRas** [comment]
@jperville Ok I am nearly done with the first piece. (Redeploy ETCD Ca/Cert on master/etcd servers)
Everything looks good. I am going to adjust the documentation and if you can give it a try will be great.
Should be with you before lunch time (y)

**Comment by jperville** [comment]
@IshentRas I will happily test and give you my feedback.

**Comment by IshentRas** [comment]
@jperville @ianmiell I will let you guys give it a try.
As described here: https://github.com/IshentRas/cookbook-openshift3#roles-examples

**Comment by IshentRas** [comment]
@jperville @ianmiell https://github.com/IshentRas/cookbook-openshift3/blob/master/certificates-process.md

**Comment by IshentRas** [comment]
The only missing logics are around:

- [ ] Redeploying router certificates
- [ ] Redeploying registry certificates
- [ ] Redeploying master/node certificates

Should not be a big deal.

**Comment by IshentRas** [comment]
@jperville @ianmiell I believe that issue can be closed?

**Comment by jperville** [comment]
I think so
