### ISSUE TITLE
Openshift

### ISSUE THREAD

**Issue by tasuki** [IshentRas/cookbook-openshift3#223]
The repo description says "Chef Cookbook for Openshit" - note the missing F in "Openshift" and the subtle change of meaning. Either this is a (not so) subtle stab at Openshift (well done!), or a typo.

**Comment by ianmiell** [comment]
This has cheered me up.

:joy:

@IshentRas I can't change this, so I guess it wasn't me 😃

**Comment by jperville** [comment]
I submit PR #224 to fix all instances of "openshit" in the code but I cannot edit the repository description, maybe @IshentRas can?

**Comment by IshentRas** [comment]
lollllllllllllllllll
