### ISSUE TITLE
Validate Failure (first_etcd)

### ISSUE THREAD

**Issue by Defilan** [IshentRas/cookbook-openshift3#229]
Hello! With the most recent update, there is now an error in the recipe compile stage when trying to deploy this cookbook. My example is for a standalone master running ose_major_version 3.6. 

The error is surrounding the code `only_if { node['cookbook-openshift3']['openshift_HA'] }`. The only_if resource is not available in plain Ruby as it's being used right now. I made a quick code change to address this and will attach this bug to the PR. 

Here are some screenshots of the bug. 

![screenshot from 2018-03-31 01-46-24](https://user-images.githubusercontent.com/7034124/38161562-23e504f8-3486-11e8-8744-b193e174322e.png)
![screenshot from 2018-03-31 01-46-41](https://user-images.githubusercontent.com/7034124/38161564-263e8a26-3486-11e8-9266-561c60509a60.png)

Thanks!

**Comment by ianmiell** [comment]
Christopher - can you send more details of your setup, so I can add this to
the regression test?

How many machines (just one?). If so, please send the environment/role json
file.

On Sat, Mar 31, 2018 at 9:53 AM, Christopher Maher <notifications@github.com
