### ISSUE TITLE
Logging support for 3.x

### ISSUE THREAD

**Issue by IshentRas** [IshentRas/cookbook-openshift3#239]
Being able to deploy logging via CHEF

**Comment by jperville** [comment]
Hello @IshentRas , do you know if any progress has been made on this issue? Thank you very much

**Comment by IshentRas** [comment]
@jperville :+1: Finishing the logic and should be with your before the end of this week.
Just finalising the logic for 3.7.

**Comment by jperville** [comment]
This new logic works very well except for #258 which I will fix very soon.
Closing this issue.
