### ISSUE TITLE
master certificate does not list FQDN as SAN for standalone master deployment

### ISSUE THREAD

**Issue by maddop** [IshentRas/cookbook-openshift3#240]
Fresh install, using standalone master and 3 nodes.

Using: 
recipe[cookbook-openshift3::default@2.0.42
"ose_major_version": "3.5"

First chef-client run on the master fails:

`[2018-05-15T14:10:41+01:00] ERROR: execute[Generate certificate for node1.lab.maddocks] (cookbook-openshift3::nodes_certificates line 67) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of /usr/bin/oc adm create-api-client-config                                                   ${legacy_certs}               --client-dir=/var/chef/cache/node1.lab.maddocks               --certificate-authority=/var/www/html/master_certs/generated_certs/ca.crt               --signer-cert=/var/www/html/master_certs/generated_certs/ca.crt --signer-key=/var/www/html/master_certs/generated_certs/ca.key               --signer-serial=/var/www/html/master_certs/generated_certs/ca.serial.txt --user='system:node:node1.lab.maddocks'               --groups=system:nodes --master=https://master1.lab.maddocks:8443 ${validity_certs} ----
STDOUT:
STDERR: error: certificate-authority must be a valid certificate file: open /var/www/html/master_certs/generated_certs/ca.crt: no such file or directory
See 'oc adm create-api-client-config -h' for help and examples.
---- End output of /usr/bin/oc adm create-api-client-config                                                     ${legacy_certs}               --client-dir=/var/chef/cache/node1.lab.maddocks               --certificate-authority=/var/www/html/master_certs/generated_certs/ca.crt               --signer-cert=/var/www/html/master_certs/generated_certs/ca.crt --signer-key=/var/www/html/master_certs/generated_certs/ca.key               --signer-serial=/var/www/html/master_certs/generated_certs/ca.serial.txt --user='system:node:node1.lab.maddocks'               --groups=system:nodes --master=https://master1.lab.maddocks:8443 ${validity_certs} ----
Ran /usr/bin/oc adm create-api-client-config                                                    ${legacy_certs}               --client-dir=/var/chef/cache/node1.lab.maddocks               --certificate-authority=/var/www/html/master_certs/generated_certs/ca.crt               --signer-cert=/var/www/html/master_certs/generated_certs/ca.crt --signer-key=/var/www/html/master_certs/generated_certs/ca.key               --signer-serial=/var/www/html/master_certs/generated_certs/ca.serial.txt --user='system:node:node1.lab.maddocks'               --groups=system:nodes --master=https://master1.lab.maddocks:8443 ${validity_certs} returned 1
[2018-05-15T14:10:41+01:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
`

Rerun of chef-client seems to generate the certificates successfully but the certificate is missing the FQDN of the master (master.lab.maddocks) from its SAN list. 

As such, the Check Master API test fails:

`curl --silent https://master1.lab.maddocks:8443/healthz/ready --cacert /etc/origin/master/ca.crt --cacert /etc/origin/master/ca-bundle.crt`

If I try this test manually using the IP address is works.

I can access the console via the browser and view the certificate, the SAN list is missing the FQDN.

Yet, if I check my /etc/origin/master/master-config.yaml it is listed under the corsAllowedOrigins

A further test, if I delete the certs from /etc/origin/master (just to test) and rerun chef-client, it generates the certificate successfully but atomic-openshift-master fails to start because it fails to get supported resources from server. Which i'm assuming is because the tokens will be incorrect in etcd?

My role:

`{
  "chef_type": "role",
  "default_attributes": {},
  "description": "Common role for all lab servers",
  "env_run_lists": {},
  "json_class": "Chef::Role",
  "name": "ose-lab",
  "override_attributes": {
    "cookbook-openshift3": {
      "deploy_example":"true",
      "deploy_example_db_templates":"true",
      "deploy_example_image-streams":"true",
      "deploy_example_quickstart-templates":"true",
      "deploy_example_xpaas-streams":"true",
      "deploy_example_xpaas-templates":"true",
      "docker_dns_search_option": ["lab.maddocks"],
      "openshift_master_sdn_cluster_network_cidr":"10.1.0.0/16",
      "openshift_master_sdn_host_subnet_length":"8",
      "master_servers": [
        {
                "fqdn":"master1.lab.maddocks",
                "ipaddress":"192.168.0.202"
        }
      ],
      "node_servers": [
        {
                "fqdn":"node1.lab.maddocks",
                "ipaddress":"192.168.0.203",
                "scheduable": true,
                "label": "region=infra"
        },
        {
                "fqdn":"node2.lab.maddocks",
                "ipaddress":"192.168.0.204",
                "scheduable": true,
                "label": "region=user"
        },
        {
                "fqdn":"node3.lab.maddocks",
                "ipaddress":"192.168.0.205",
                "scheduable": true,
                "label": "region=user"
        }
      ],
      "osn_cluster_dns_ip": "172.17.0.1",
      "openshift_cluster_name": "console.appcloud.lab.maddocks",
      "openshift_common_portal_net": "172.17.0.0/16",
      "openshift_master_console_url": "https://console.appcloud.lab.maddocks:8443/console",
      "openshift_master_public_api_url": "https://console.appcloud.lab.maddocks:8443",
      "openshift_common_api_hostname": "master1.lab.maddocks",
      "openshift_common_public_hostname":"master1.lab.maddocks",
      "openshift_master_router_subdomain": "appcloud.lab.maddocks",
      "ose_major_version": "3.5"
    }
  },
  "run_list": [
    "recipe[cookbook-openshift3::default@2.0.42]"
  ]
}
`

thanks.

**Comment by IshentRas** [comment]
Thanks @maddop for reporting :+1: 
It has now been fixed.

**Comment by ianmiell** [comment]
Should this have been caught by the kitchen tests?

**Comment by IshentRas** [comment]
@ianmiell (Un)fortunately we do not test standalone deployment. That deployment has been deprecated starting 3.6 (etcd3) or 3.7 and therefore we did not put too much attention when refactoring.
That commit 2342732 ensures version before are all OK and logic is retained.

**Comment by ianmiell** [comment]
OK, I guess no need to pursue then.
