### ISSUE TITLE
Upgrading from v1.0.42 to v2.0.42

### ISSUE THREAD

**Issue by tpolekhin** [IshentRas/cookbook-openshift3#241]
Hello!

Im currently updating our cookbook to the newest version with intention to upgrade openshift cluster from 1.4 to 3.7. Currently i've uploaded v2.0.42 to chef server and just target it in environment.

Currently masters and nodes failing with:
```
ERROR: resource template[/etc/origin/cloudprovider/aws.conf] is configured to notify resource service[origin-node] with action restart, but service[origin-node] cannot be found in the resource collection. template[/etc/origin/cloudprovider/aws.conf] is defined in /var/chef/cache/cookbooks/cookbook-openshift3/recipes/cloud_provider.rb:28:in `from_file'
```

Fixing it now by adding
```
service "#{node['cookbook-openshift3']['openshift_service_type']}-node"
```
to services.rb

I will update this with all the issues i face during the run

**Comment by tpolekhin** [comment]
Defaults for these attributes has changed
```
['cookbook-openshift3']['openshift_master_sdn_cluster_network_cidr']
['cookbook-openshift3']['openshift_master_sdn_host_subnet_length']
```

**Comment by ianmiell** [comment]
Hi, yes, there are a subset of attributes that should not be changed. We intend to add more checking to the validate script to ensure that this does not happen on existing clusters. Thanks for raising, it will give us more motivation to pursue that work. Ian

**Comment by tpolekhin** [comment]
Okay, so i followed upgrade instructions:

1. Set up upgrade attributes:
```
cookbook-openshift3:
  control_upgrade:                           true
  control_upgrade_flag:                      /tmp/upgrade-from-14-to-15
  control_upgrade_version:                   15
```

2. Created `control_upgrade_flag` on control plane: etcd and master instances
```
touch /tmp/upgrade-from-14-to-15
```

3. Chef run was successful on all instances.
```
INFO: Upgrade for MASTERS [STARTED]
...
Upgrade for MASTERS [COMPLETED]
...
Upgrade for NODE [STARTED]
...
Upgrade for NODE [COMPLETED]
```

4. After that i removed control_upgrade flags from attributes, and changed main version:
```
openshift_docker_image_version:            v1.5.1
ose_major_version:                         1.5
ose_version:                               1.5.1-1.el7
```

5. Next chef run on all instances except for etcd i got this:
```
yum_package[origin-master] installing origin-master-1.5.1-1.el7 from centos-openshift-origin15 repository
yum[82106]: Updated: krb5-libs-1.15.1-19.el7.x86_64
yum[82106]: Installed: libtdb-1.3.15-1.el7.x86_64
groupadd[82409]: group added to /etc/group: name=printadmin, GID=989
groupadd[82409]: group added to /etc/gshadow: name=printadmin
groupadd[82409]: new group: name=printadmin, GID=989
yum[82106]: Installed: samba-common-4.7.1-6.el7.noarch
yum[82106]: Installed: avahi-libs-0.6.31-19.el7.x86_64
yum[82106]: Updated: libtevent-0.9.33-2.el7.x86_64
yum[82106]: Installed: libldb-1.2.2-1.el7.x86_64
yum[82106]: Installed: 1:cups-libs-1.6.3-35.el7.x86_64
yum[82106]: Installed: samba-common-libs-4.7.1-6.el7.x86_64
yum[82106]: Installed: libwbclient-4.7.1-6.el7.x86_64
yum[82106]: Installed: samba-client-libs-4.7.1-6.el7.x86_64
yum[82106]: Installed: cifs-utils-6.2-10.el7.x86_64
yum[82106]: Updated: origin-clients-3.9.0-1.el7.git.0.ba7faec.x86_64
yum[82106]: Updated: origin-3.9.0-1.el7.git.0.ba7faec.x86_64
yum[82106]: Installed: origin-node-3.9.0-1.el7.git.0.ba7faec.x86_64
yum[82106]: Updated: 1:openvswitch-2.6.1-3.git20161206.el7.x86_64
yum[82106]: Updated: origin-sdn-ovs-3.9.0-1.el7.git.0.ba7faec.x86_64
yum[82106]: Updated: origin-master-3.9.0-1.el7.git.0.ba7faec.x86_64
yum[82106]: Erased: tuned-profiles-origin-node-1.4.1-1.el7.x86_64
chef-client[40460]: [2018-05-17T18:22:30+00:00] INFO: yum_package[origin-master] installed origin-master at 1.5.1-1.el7
```
```
================================================================================
Error executing action `install` on resource 'yum_package[origin-clients]'
================================================================================
Chef::Exceptions::Package
-------------------------
Installed package origin-clients-3.9.0-1.el7.git.0.ba7faec is newer than candidate package origin-clients-1.5.1-1.el7
Cookbook Trace:
```

any suggestions?

**Comment by ianmiell** [comment]
```
Installed package origin-clients-3.9.0-1.el7.git.0.ba7faec is newer than candidate package origin-clients-1.5.1-1.el7
```

Looks like you have oc client 3.9 installed - does a `yum history` give a clue how this happened?

**Comment by tpolekhin** [comment]
None, I thought that cookbook installes all of them and the picks up correct one based on version I’m installing? I guess I was wrong(

So I MUST set a correct repository in the attributes when I do version upgrade?

**Comment by IshentRas** [comment]
Yes you need to. Can you please send over your list of attributes (environment or role?)
I would like to check what you have got setup

**Comment by IshentRas** [comment]
You also need to remove the flag stuff... (Just put an underscore before the variable name)
That is why it tries to update again....
cookbook-openshift3:
  control_upgrade:                           true
  _control_upgrade_flag:                      /tmp/upgrade-from-14-to-15
  control_upgrade_version:                   15

**Comment by tpolekhin** [comment]
```
chef_type:           environment
cookbook_versions:
  cookbook-openshift3:               = 2.0.42
default_attributes:
  chef_client:
    config:
      chef_server_url: < chef server url >
    interval: 600
    splay:    60
  cookbook-openshift3:
    deploy_containerized:                      false
    deploy_dnsmasq:                            true
    deploy_example:                            false
    docker_version:                            1.10.3-59.el7.centos
    etcd_servers:
      fqdn:      ip-10-239-122-109.ec2.internal
      ipaddress: 10.239.122.109

      fqdn:      ip-10-239-122-158.ec2.internal
      ipaddress: 10.239.122.158

      fqdn:      ip-10-239-122-172.ec2.internal
      ipaddress: 10.239.122.172
    master_servers:
      fqdn:        ip-10-239-122-115.ec2.internal
      ipaddress:   10.239.122.115
      labels:      region=primary
      schedulable: false

      fqdn:        ip-10-239-122-134.ec2.internal
      ipaddress:   10.239.122.134
      labels:      region=primary
      schedulable: false

      fqdn:        ip-10-239-122-175.ec2.internal
      ipaddress:   10.239.122.175
      labels:      region=primary
      schedulable: false
    node_servers:
      fqdn:      ip-10-239-122-141.ec2.internal
      ipaddress: 10.239.122.141
      labels:    region=primary

      fqdn:        ip-10-239-122-115.ec2.internal
      ipaddress:   10.239.122.115
      labels:      region=primary
      schedulable: false

      fqdn:      ip-10-239-122-100.ec2.internal
      ipaddress: 10.239.122.100
      labels:    region=infra

      fqdn:        ip-10-239-122-134.ec2.internal
      ipaddress:   10.239.122.134
      labels:      region=primary
      schedulable: false

      fqdn:      ip-10-239-122-153.ec2.internal
      ipaddress: 10.239.122.153
      labels:    region=infra

      fqdn:        ip-10-239-122-175.ec2.internal
      ipaddress:   10.239.122.175
      labels:      region=primary
      schedulable: false

      fqdn:      ip-10-239-122-177.ec2.internal
      ipaddress: 10.239.122.177
      labels:    region=infra

      fqdn:      ip-10-239-122-101.ec2.internal
      ipaddress: 10.239.122.101
      labels:    region=primary

      fqdn:      ip-10-239-122-174.ec2.internal
      ipaddress: 10.239.122.174
      labels:    region=primary
    oauth_Identities:
      HTPasswdPasswordIdentityProvider
      GitHubIdentityProvider
    openshift_HA:                              true
    openshift_cloud_provider:                  aws
    openshift_cluster_name:                    < internal master elb >
    openshift_common_default_nodeSelector:     region=primary
    openshift_common_public_hostname:          < external master elb >
    openshift_deployment_type:                 origin
    openshift_docker_image_version:            v1.5.1
    openshift_hosted_cluster_metrics:          false
    openshift_hosted_manage_registry:          false
    openshift_master_ca_certificate:
      data_bag_item_name: ca
      data_bag_name:      certificates
    openshift_master_console_url:              < external master elb >
    openshift_master_debug_level:              2
    openshift_master_public_api_url:           < external master elb >
    openshift_master_router_subdomain:         < router domain >
    openshift_master_sdn_cluster_network_cidr: 10.1.0.0/16
    openshift_master_sdn_host_subnet_length:   8
    openshift_node_cadvisor_port:              4194
    openshift_node_debug_level:                2
    openshift_node_image_gc_high_threshold:    60
    openshift_node_image_gc_low_threshold:     50
    openshift_node_max_pod:                    500
    openshift_node_read_only_port:             10255
    ose_major_version:                         1.5
    ose_version:                               1.5.1-1.el7
description:         qa-001-us-east-1 environment
json_class:          Chef::Environment
name:                qa-001-us-east-1
```

**Comment by tpolekhin** [comment]
Im trying to rollback packets to v1.4 but chef keeps installing latest packets v3.9.0
I checked available packets with `yum search --showduplicates origin-node`
```
origin-node-1.4.1-1.el7.x86_64 : Origin Node
origin-node-1.5.1-1.el7.x86_64 : Origin Node
origin-node-3.6.0-1.0.c4dd4cf.x86_64 : Origin Node
origin-node-3.6.1-1.0.008f2d5.x86_64 : Origin Node
origin-node-3.7.0-1.0.7ed6862.x86_64 : Origin Node
origin-node-3.7.1-1.el7.git.0.0a2d6a1.x86_64 : Origin Node
origin-node-3.7.1-2.el7.x86_64 : Origin Node
origin-node-3.8.0-1.el7.git.0.dd1558c.x86_64 : Origin Node
origin-node-3.9.0-1.el7.git.0.ba7faec.x86_64 : Origin Node
origin-node-3.9.0-1.el7.git.0.ba7faec.x86_64 : Origin Node
```

**Comment by tpolekhin** [comment]
something weird in dependencies
```
yum install origin-node-1.4.1-1.el7
Failed to set locale, defaulting to C
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: packages.oit.ncsu.edu
 * epel: ewr.edge.kernel.org
 * extras: mirror.ash.fastserv.com
 * updates: mirror.ash.fastserv.com
Resolving Dependencies
--> Running transaction check
---> Package origin-node.x86_64 0:1.4.1-1.el7 will be installed
--> Processing Dependency: tuned-profiles-origin-node = 1.4.1-1.el7 for package: origin-node-1.4.1-1.el7.x86_64
--> Processing Dependency: origin = 1.4.1-1.el7 for package: origin-node-1.4.1-1.el7.x86_64
--> Running transaction check
---> Package origin.x86_64 0:1.4.1-1.el7 will be installed
--> Processing Dependency: origin-clients = 1.4.1-1.el7 for package: origin-1.4.1-1.el7.x86_64
---> Package origin-node.x86_64 0:3.9.0-1.el7.git.0.ba7faec will be installed
--> Processing Dependency: origin = 3.9.0-1.el7.git.0.ba7faec for package: origin-node-3.9.0-1.el7.git.0.ba7faec.x86_64
--> Running transaction check
---> Package origin.x86_64 0:1.4.1-1.el7 will be installed
---> Package origin.x86_64 0:3.9.0-1.el7.git.0.ba7faec will be installed
--> Processing Dependency: origin-clients = 3.9.0-1.el7.git.0.ba7faec for package: origin-3.9.0-1.el7.git.0.ba7faec.x86_64
---> Package origin-clients.x86_64 0:1.4.1-1.el7 will be installed
--> Running transaction check
---> Package origin-clients.x86_64 0:3.9.0-1.el7.git.0.ba7faec will be installed
--> Finished Dependency Resolution

Dependencies Resolved
```

**Comment by IshentRas** [comment]
can you : 'ls -l /etc/yum.repos.d'

**Comment by tpolekhin** [comment]
```
ls -l /etc/yum.repos.d
total 52
-rw-r--r--. 1 root root 1664 Dec  9  2015 CentOS-Base.repo
-rw-r--r--. 1 root root 1309 Dec  9  2015 CentOS-CR.repo
-rw-r--r--. 1 root root  649 Dec  9  2015 CentOS-Debuginfo.repo
-rw-r--r--. 1 root root  630 Dec  9  2015 CentOS-Media.repo
-rw-r--r--. 1 root root 1331 Dec  9  2015 CentOS-Sources.repo
-rw-r--r--. 1 root root 1952 Dec  9  2015 CentOS-Vault.repo
-rw-r--r--. 1 root root  290 Dec  9  2015 CentOS-fasttrack.repo
-rw-r--r--. 1 root root  259 Apr 20  2017 centos-openshift-origin.repo
-rw-r--r--. 1 root root  265 May 17 10:56 centos-openshift-origin14.repo
-rw-r--r--. 1 root root  265 May 17 18:21 centos-openshift-origin15.repo
-rw-r--r--. 1 root root  240 Apr 20  2017 datadog.repo
-rw-r--r--. 1 root root 1056 Dec 27  2016 epel-testing.repo
-rw-r--r--. 1 root root  957 Dec 27  2016 epel.repo
```

**Comment by IshentRas** [comment]
Can you cat centos-openshift-origin.repo ?

**Comment by tpolekhin** [comment]
```
cat /etc/yum.repos.d/centos-openshift-origin.repo
# This file was generated by Chef
# Do NOT modify this file by hand.

[centos-openshift-origin]
name=Centos-openshift-origin aPaaS Repository
baseurl=http://mirror.centos.org/centos/7/paas/x86_64/openshift-origin/
enabled=1
fastestmirror_enabled=0
gpgcheck=0
```

**Comment by IshentRas** [comment]
That is your issue get rid of it :-1: 
It has got too many packages

**Comment by tpolekhin** [comment]
any idea where it came from?
this cluster was setup using this cookbook at v1.10.42
is this what you used back then?

**Comment by IshentRas** [comment]
I do not know. I believe before we did not know what we were doing :-)
Thanks to @ianmiell we have put a lot of effort on our tests and QA.

**Comment by tpolekhin** [comment]
okay, so i reverted cluster to a initial state on v1.4
i ran `oc adm diagnostics` and everything passed

i've added control upgrade attributes back to environment in chef
```
    control_upgrade:                           true
    control_upgrade_flag:                      /tmp/upgrade-from-14-to-15
    control_upgrade_version:                   15
```

all chef run succeed, but nothing upgraded
i checked `/etc/yum.repos.d/` and there's no repo for 1.5, only for 1.4

am i missing something again?

**Comment by tpolekhin** [comment]
i've added upgrade_repos for the attributes:
```
    upgrade_repos:
      baseurl:  http://mirror.centos.org/centos/7/paas/x86_64/openshift-origin15/
      gpgcheck: false
      name:     centos-openshift-origin15
```
but nothing changed(

chef just won't add this repo:
```
...
Recipe: cookbook-openshift3::packages
  * yum_repository[centos-openshift-origin14] action create
    * template[/etc/yum.repos.d/centos-openshift-origin14.repo] action create (up to date)
    * execute[yum clean metadata centos-openshift-origin14] action nothing (skipped due to action :nothing)
    * execute[yum-makecache-centos-openshift-origin14] action nothing (skipped due to action :nothing)
    * ruby_block[yum-cache-reload-centos-openshift-origin14] action nothing (skipped due to action :nothing)
     (up to date)
Recipe: cookbook-openshift3::upgrade_control_plane15
  * execute[Disable origin-excluder (Best effort < 3.5)] action run (skipped due to only_if)
  * execute[Disable origin-docker-excluder (Best effort < 3.5)] action run (skipped due to only_if)
  * log[Upgrade for MASTERS [STARTED]] action write
...
```

**Comment by IshentRas** [comment]
Starting investigating. Will come back to you ASAP.

**Comment by IshentRas** [comment]
control_upgrade: true
    control_upgrade_version: '15'
    control_upgrade_flag: "/tmp/ready15"
    upgrade_repos:
    - name: centos-openshift-origin15
      baseurl: http://mirror.centos.org/centos/7/paas/x86_64/openshift-origin15/
      gpgcheck: false

**Comment by IshentRas** [comment]
@tpolekhin You missed a '-' on the upgrade_repos. It should be an array not a hash.
    upgrade_repos:
    - baseurl: 'http://mirror.centos.org/centos/7/paas/x86_64/openshift-origin15/'
      gpgcheck: false
      name:     'centos-openshift-origin15'

**Comment by tpolekhin** [comment]
This is just how knife show outputs it. I Json it is array with {} object inside

**Comment by tpolekhin** [comment]
```
knife environment show qa-001-us-east-1 --format json
"default_attributes": {
    "cookbook-openshift3": {
      "control_upgrade": true,
      "control_upgrade_version": "15",
      "control_upgrade_flag": "/tmp/upgrade-from-14-to-15",
      "upgrade_repos": [
        {
          "gpgcheck": false,
          "name": "centos-openshift-origin15",
          "baseurl": "http://mirror.centos.org/centos/7/paas/x86_64/openshift-origin15/"
        }
      ],
```

**Comment by IshentRas** [comment]
I have created a 1.4 cluster and run an upgrade to 1.5 (Everything worked as expected so I need to check what is wrong with your setup.

Recipe: yum::default
  * yum_globalconfig[/etc/yum.conf] action create
    * template[/etc/yum.conf] action create (up to date)
     (up to date)
Recipe: cookbook-openshift3::packages
  * yum_repository[centos-openshift-origin15] action create
    * template[/etc/yum.repos.d/centos-openshift-origin15.repo] action create
      - create new file /etc/yum.repos.d/centos-openshift-origin15.repo
      - update content in file /etc/yum.repos.d/centos-openshift-origin15.repo from none to a97776
      --- /etc/yum.repos.d/centos-openshift-origin15.repo	2018-05-18 08:29:40.346105280 +0100
      +++ /etc/yum.repos.d/.chef-centos-openshift-origin1520180518-4071-1hf7ny8.repo	2018-05-18 08:29:40.345105278 +0100
      @@ -1 +1,10 @@
      +# This file was generated by Chef
      +# Do NOT modify this file by hand.
      +
      +[centos-openshift-origin15]
      +name=Centos-openshift-origin15 aPaaS Repository
      +baseurl=http://mirror.centos.org/centos/7/paas/x86_64/openshift-origin15/
      +enabled=1
      +fastestmirror_enabled=0
      +gpgcheck=0
      - change mode from '' to '0644'
      - restore selinux security context
    * execute[yum clean metadata centos-openshift-origin15] action run
      - execute yum clean metadata --disablerepo=* --enablerepo=centos-openshift-origin15
    * execute[yum-makecache-centos-openshift-origin15] action run
      - execute yum -q -y makecache --disablerepo=* --enablerepo=centos-openshift-origin15
    * ruby_block[yum-cache-reload-centos-openshift-origin15] action create
      - execute the ruby block yum-cache-reload-centos-openshift-origin15
    * execute[yum clean metadata centos-openshift-origin15] action nothing (skipped due to action :nothing)
    * execute[yum-makecache-centos-openshift-origin15] action nothing (skipped due to action :nothing)
    * ruby_block[yum-cache-reload-centos-openshift-origin15] action nothing (skipped due to action :nothing)
  
Recipe: cookbook-openshift3::upgrade_control_plane15
  * execute[Disable origin-excluder (Best effort < 3.5)] action run (skipped due to only_if)
  * execute[Disable origin-docker-excluder (Best effort < 3.5)] action run (skipped due to only_if)
  * log[Upgrade for ETCD [STARTED]] action write
  
  * execute[Generate etcd backup before upgrade] action run
    - execute etcdctl backup --data-dir=/var/lib/etcd --backup-dir=/var/lib/etcd-pre-upgrade15
  * execute[Copy etcd v3 data store (PRE)] action run
    - execute cp -a /var/lib/etcd/member/snap/db /var/lib/etcd-pre-upgrade15/member/snap/
  * execute[Copy etcd v3 data store (PRE)] action nothing (skipped due to action :nothing)
Recipe: cookbook-openshift3::etcd_packages
  * yum_package[etcd] action install (up to date)
  * yum_package[etcd] action install (up to date)
  * cookbook_file[/etc/profile.d/etcdctl.sh] action create (up to date)
Recipe: cookbook-openshift3::etcd_cluster
  * iptables_rule[firewall_etcd] action enable

**Comment by tpolekhin** [comment]
What did you do to run upgrade?
What i did is added control_upgrade attributes as above,
and created flag files on etcd and master nodes `touch /tmp/upgrade-from-14-to-15`

Is that suppose to be enough?

**Comment by tpolekhin** [comment]
moved `control_upgrade` attributes from `default_attributes` to `override_attributes` in environment to mach the example. did not helped

**Comment by IshentRas** [comment]
@tpolekhin Would it help if we can talk directly? can you send me your email?

**Comment by tpolekhin** [comment]
The issue with chef upgrade logic was in outdated version of chef-client v12.11.18
After upgrading chef-client version to v12.17.44 upgrade logic works as expected

**Comment by IshentRas** [comment]
Feel free to ping us when needed :+1: 
Thanks for your feedback we shall add more checks to it. #243 has been created to cover that matter/

**Comment by tpolekhin** [comment]
post here for consistency:

after upgrade to 3.6 origin-node process fails with:
`failed to run Kubelet: failed to create kubelet: misconfiguration: kubelet cgroup driver: "systemd" is different from docker cgroup driver: "cgroupfs"`

```
docker version
Client:
 Version:         1.10.3
 API version:     1.22
 Package version: docker-common-1.10.3-59.el7.centos.x86_64
 Go version:      go1.6.3
 Git commit:      3999ccb-unsupported
 Built:           Thu Dec 15 17:24:43 2016
 OS/Arch:         linux/amd64

Server:
 Version:         1.10.3
 API version:     1.22
 Package version: docker-common-1.10.3-59.el7.centos.x86_64
 Go version:      go1.6.3
 Git commit:      3999ccb-unsupported
 Built:           Thu Dec 15 17:24:43 2016
 OS/Arch:         linux/amd64
```

```
cat /usr/lib/systemd/system/docker.service
...
ExecStart=/usr/bin/docker-current daemon \
          --exec-opt native.cgroupdriver=systemd \
...
```

tried to upgrade docker version to 1.12.6 but failed to find packets for docker in origin repos

i have a feeling that i saw docker packets before in origin repos, maybe they got removed...

**Comment by tpolekhin** [comment]
this guy has a similar issue with docker 1.12 not available in centos repos anymore
https://github.com/openshift/openshift-ansible/issues/8342

**Comment by tpolekhin** [comment]
found docker-1.12.6 http://vault.centos.org/7.3.1611/extras/x86_64/Packages/

**Comment by IshentRas** [comment]
@tpolekhin I forgot to tell you yesterday to remove the line:
docker_version:                            1.10.3-59.el7.centos
You do not need that repository.
The only thing you need is located within the extra repository (Should be there by default)
In case it is not:
#additional packages that may be useful
[extras]
name=CentOS-$releasever - Extras
mirrorlist=http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=extras&infra=$infra
#baseurl=http://mirror.centos.org/centos/$releasever/extras/$basearch/
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7

**Comment by tpolekhin** [comment]
Extras has only docker 1.13.1 - is this what I should have now? One of my guys that runs rhel openshift said that docker 1.13 breaks everything

**Comment by IshentRas** [comment]
No it is fine.
Will be suitable as you are upgrading 1.5 3.6 etc..

**Comment by tpolekhin** [comment]
Okay, thanks!

**Comment by tpolekhin** [comment]
faced this issue after upgrading from 1.5 to 3.6
https://bugzilla.redhat.com/show_bug.cgi?id=1467775

tried to clean everything out(except for etcd) and reinstall - no luck(

any suggestions?

**Comment by IshentRas** [comment]
Hey,

Sorry for my late reply as I have been busy with other topics.
Look I am available when you are.
Just let me know when it is convenient and I am going to help/assist
you debug that problem.

William

**Comment by tpolekhin** [comment]
upgrade from 3.6 to 3.7 fails on first master with:
```
Recipe: cookbook-openshift3::upgrade_control_plane37_part2
  * log[Pre master upgrade - Upgrade all storage] action write

  * execute[Confirm OpenShift authorization objects are in sync] action run
    - execute /usr/bin/oc adm             --config=/etc/origin/master/admin.kubeconfig             migrate authorization
  * execute[Migrate storage post policy reconciliation] action run
    - execute /usr/bin/oc adm             --config=/etc/origin/master/admin.kubeconfig             migrate storage --include=* --confirm
  * execute[Create key for upgrade all storage] action run

    ================================================================================
    Error executing action `run` on resource 'execute[Create key for upgrade all storage]'
    ================================================================================

    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '128'
    ---- Begin output of ETCDCTL_API=3 /usr/bin/etcdctl --cert /etc/etcd/peer.crt --key /etc/etcd/peer.key --cacert /etc/etcd/ca.crt --endpoints https://`hostname`:2379 put /migration/storage ok ----
    STDOUT:
    STDERR: Error:  open /etc/etcd/peer.crt: no such file or directory
    ---- End output of ETCDCTL_API=3 /usr/bin/etcdctl --cert /etc/etcd/peer.crt --key /etc/etcd/peer.key --cacert /etc/etcd/ca.crt --endpoints https://`hostname`:2379 put /migration/storage ok ----
    Ran ETCDCTL_API=3 /usr/bin/etcdctl --cert /etc/etcd/peer.crt --key /etc/etcd/peer.key --cacert /etc/etcd/ca.crt --endpoints https://`hostname`:2379 put /migration/storage ok returned 128
```

there's no peer files on master in `/etc/etcd` folder, like on `etcd` nodes, only `ca` folder:
```
ls -ls /etc/etcd/
drwx------. 5 root root 212 May 31 13:00 ca
```

**Comment by tpolekhin** [comment]
also, this
https://github.com/IshentRas/cookbook-openshift3/blob/master/recipes/upgrade_control_plane37_part2.rb#L38
this
https://github.com/IshentRas/cookbook-openshift3/blob/master/recipes/upgrade_control_plane37_part2.rb#L45
and this
https://github.com/IshentRas/cookbook-openshift3/blob/master/recipes/upgrade_control_plane37_part2.rb#L76
all run on master, but use different etcd certificates

i think first 2 should be corrected to match 3rd

**Comment by tpolekhin** [comment]
upgrade from 3.6 to 3.7 fails on master nodes with:
```
Recipe: cookbook-openshift3::master_packages
  * yum_package[origin-master] action install
    - install version 3.7.1-2.el7 of package origin-master
Recipe: cookbook-openshift3::services
  * execute[daemon-reload] action run
    - execute systemctl daemon-reload
Recipe: cookbook-openshift3::master_packages
  * yum_package[origin-clients] action install

    ================================================================================
    Error executing action `install` on resource 'yum_package[origin-clients]'
    ================================================================================

    Chef::Exceptions::Package
    -------------------------
    Installed package origin-clients-3.7.2-1.el7.git.0.cd74924 is newer than candidate package origin-clients-3.7.1-2.el7
```

**Comment by IshentRas** [comment]
@tpolekhin  thanks checking and correcting ASAP

**Comment by tpolekhin** [comment]
for some reason origin-node did not updated on master nodes, while control plane did
```
Recipe: cookbook-openshift3::upgrade_node37
  * log[Upgrade for NODE [STARTED]] action write

  * execute[Disable origin-excluder] action run
    - execute origin-excluder enable
  * execute[Disable origin-docker-excluder] action run
    - execute origin-docker-excluder enable
Recipe: cookbook-openshift3::node
  * ruby_block[Turn off SWAP for nodes] action run (skipped due to only_if)
  * file[/usr/local/etc/.firewall_node_additional.txt] action create (up to date)
  * iptables_rule[firewall_node] action enable
    * template[/etc/iptables.d/firewall_node] action create (up to date)
     (up to date)
  * directory[/etc/origin/node] action create (up to date)
  * template[/etc/systemd/system/origin-node.service] action create (up to date)
  * template[/etc/sysconfig/origin-node] action create (up to date)
  * yum_package[origin-node] action install (up to date)
  * yum_package[origin-sdn-ovs] action install (up to date)
  * yum_package[conntrack-tools] action install (up to date)
  * remote_file[Retrieve certificate from Master[ip-10-239-122-113.ec2.internal]] action create_if_missing (up to date)
  * execute[Un-encrypt node certificate tgz files] action nothing (skipped due to action :nothing)
  * execute[Extract certificate to Node folder] action nothing (skipped due to action :nothing)
```

**Comment by tpolekhin** [comment]
btw, i changes this https://github.com/IshentRas/cookbook-openshift3/blob/master/attributes/update.rb#L44
to be `default['cookbook-openshift3']['upgrade_ose_version'] = '3.7.2-1.el7.git.0.cd74924'` to make it work for the control plane

**Comment by tpolekhin** [comment]
i think this still needs to be changed:
https://github.com/IshentRas/cookbook-openshift3/blob/master/recipes/cloud_provider.rb#L34

there's no `service[#{node['cookbook-openshift3']['openshift_service_type']}-node]` in `services.rb`

**Comment by IshentRas** [comment]
Thanks. Fixed

**Comment by tpolekhin** [comment]
tried to utilize wildcard node certificate but failed with:
```
Jun 04 11:39:41 ip-10-239-122-113.ec2.internal origin-node[99371]: E0604 11:39:41.674334   99371 kubelet_node_status.go:106] Unable to register node "ip-10-239-122-113.ec2.internal" with API server: nodes "ip-10-239-122-113.ec2.internal" is forbidden: node wildcard_nodes cannot modify node ip-10-239-122-113.ec2.internal
```

is thee some additional config needs to be done?

**Comment by tpolekhin** [comment]
@ianmiell @IshentRas kind bump :)

**Comment by IshentRas** [comment]
We are 2.0.70 now lol

**Comment by IshentRas** [comment]
@tpolekhin Sorry for this long wait. Busy with other topics...

So you are right it does not work with 3.7 out of the box because 3.7 enforce [NodeRestriction](https://kubernetes.io/docs/admin/admission-controllers/#noderestriction) admission plugin prevent the API to use a different name than the real hostname of the node. Therefore the wildcard trick name does not work as it does not match the real name of your node.
system:node:wildcrad_nodes, which uses the system:node:<nodeName> format, but does not match the actual name of your node (ip-10-239-122-113.ec2.internal)

You can disable it (Not recommended) :-1: 
admissionConfig:
  pluginConfig:
    NodeRestriction:
      configuration:
        kind: DefaultAdmissionConfig
        apiVersion: v1
        disable: true

Let me check if we can do something else instead :+1: 
Obviously it is specific to 3.7+

**Comment by IshentRas** [comment]
Closing this topic. Coming work for 3.10 fixes that issue with node bootstrapping support.
https://docs.openshift.com/container-platform/3.10/architecture/infrastructure_components/kubernetes_infrastructure.html#node-bootstrapping
