### ISSUE TITLE
insecure registries attribute

### ISSUE THREAD

**Issue by mkozinenko** [IshentRas/cookbook-openshift3#244]
I would suggest removing a portal_net attribute as insecure registry by default here: https://github.com/IshentRas/cookbook-openshift3/blob/master/attributes/default.rb#L108.
and have that attribute to be strictly configured or empty.

If we have an SSL secured internal registry, that may cause attempts to fallback to HTTP (and normally you don't have http configured for SSL secured registry). That will cause " Failed to pull image "xxx/yyyy@sha256:zzzzz": Get http://internal-registry.default.svc.cluster.local/v2/: dial tcp 172.XX.XX.XX:80: getsockopt: no route to host" in case of short network or service disruptions, instead of retrying to download layer.

**Comment by IshentRas** [comment]
@mkozinenko Good point. Will adjust and send an update

**Comment by IshentRas** [comment]
@mkozinenko Next logic is to give people the opportunity to add their self-signed registry certificates within the /etc/docker/certs.d/
