### ISSUE TITLE
Restrict permissions to certificate security files

### ISSUE THREAD

**Issue by taylok** [IshentRas/cookbook-openshift3#252]
The permissions on crt files within the master config directory are too open. 

For example: 
/etc/origin/master/ca.crt
owner: root,
group: root,
mode: 0644       desired mode: 0640

Can these be made more restrictive without breaking anything. 

Also: 
/etc/origin
owner: root,
group: root,
mode: 0755      desired mode: 0750

**Comment by IshentRas** [comment]
@taylok 
All good: Should be in the next release:

`[root@centos ~]# ls -l /etc/origin -d
drwxr-x---. 4 root root 79 Aug  1 18:24 /etc/origin
[root@centos ~]# ls -l /etc/origin/master/*.crt
-rw-r-----. 1 root root 1119 Jul 31 19:00 /etc/origin/master/admin.crt
-rw-r-----. 1 root root 1070 Jul 31 19:00 /etc/origin/master/ca-bundle.crt
-rw-r-----. 1 root root 1070 Jul 31 19:00 /etc/origin/master/ca.crt
-rw-r-----. 1 root root 2587 Jul 31 19:00 /etc/origin/master/etcd.server.crt
-rw-r-----. 1 root root 1895 Jul 31 19:00 /etc/origin/master/master.etcd-ca.crt
-rw-r-----. 1 root root 5840 Jul 31 19:00 /etc/origin/master/master.etcd-client.crt
-rw-r-----. 1 root root 1135 Jul 31 19:00 /etc/origin/master/master.kubelet-client.crt
-rw-r-----. 1 root root 1086 Jul 31 19:00 /etc/origin/master/master.proxy-client.crt
-rw-r-----. 1 root root 2571 Jul 31 19:00 /etc/origin/master/master.server.crt
-rw-r-----. 1 root root 1168 Jul 31 19:00 /etc/origin/master/openshift-master.crt
-rw-r-----. 1 root root 2372 Jul 31 19:01 /etc/origin/master/registry.crt
-rw-r-----. 1 root root 1115 Jul 31 19:00 /etc/origin/master/service-signer.crt
[root@centos ~]# ls -l /etc/origin/master/*.{crt,key}
-rw-r-----. 1 root root 1119 Jul 31 19:00 /etc/origin/master/admin.crt
-rw-------. 1 root root 1675 Jul 31 19:00 /etc/origin/master/admin.key
-rw-r-----. 1 root root 1070 Jul 31 19:00 /etc/origin/master/ca-bundle.crt
-rw-r-----. 1 root root 1070 Jul 31 19:00 /etc/origin/master/ca.crt
-rw-------. 1 root root 1675 Jul 31 19:00 /etc/origin/master/ca.key
-rw-r-----. 1 root root 2587 Jul 31 19:00 /etc/origin/master/etcd.server.crt
-rw-------. 1 root root 1675 Jul 31 19:00 /etc/origin/master/etcd.server.key
-rw-r-----. 1 root root 1895 Jul 31 19:00 /etc/origin/master/master.etcd-ca.crt
-rw-r-----. 1 root root 5840 Jul 31 19:00 /etc/origin/master/master.etcd-client.crt
-rw-------. 1 root root 1704 Jul 31 19:00 /etc/origin/master/master.etcd-client.key
-rw-r-----. 1 root root 1135 Jul 31 19:00 /etc/origin/master/master.kubelet-client.crt
-rw-------. 1 root root 1679 Jul 31 19:00 /etc/origin/master/master.kubelet-client.key
-rw-r-----. 1 root root 1086 Jul 31 19:00 /etc/origin/master/master.proxy-client.crt
-rw-------. 1 root root 1679 Jul 31 19:00 /etc/origin/master/master.proxy-client.key
-rw-r-----. 1 root root 2571 Jul 31 19:00 /etc/origin/master/master.server.crt
-rw-------. 1 root root 1675 Jul 31 19:00 /etc/origin/master/master.server.key
-rw-r-----. 1 root root 1168 Jul 31 19:00 /etc/origin/master/openshift-master.crt
-rw-------. 1 root root 1675 Jul 31 19:00 /etc/origin/master/openshift-master.key
-rw-r-----. 1 root root 2372 Jul 31 19:01 /etc/origin/master/registry.crt
-rw-------. 1 root root 1679 Jul 31 19:01 /etc/origin/master/registry.key
-rw-------. 1 root root 1675 Jul 31 19:00 /etc/origin/master/serviceaccounts.private.key
-rw-------. 1 root root  459 Jul 31 19:00 /etc/origin/master/serviceaccounts.public.key
-rw-r-----. 1 root root 1115 Jul 31 19:00 /etc/origin/master/service-signer.crt
-rw-------. 1 root root 1679 Jul 31 19:00 /etc/origin/master/service-signer.key
`

**Comment by IshentRas** [comment]
Fixed in https://github.com/IshentRas/cookbook-openshift3/commit/55245a789a6083337763bf456df638b2eccd0a7c
