### ISSUE TITLE
Restrict permission for policy and scheduler in config directory

### ISSUE THREAD

**Issue by taylok** [IshentRas/cookbook-openshift3#257]
/etc/origin/master/scheduler.json
owner: root,
group: root,
mode: 0644 desired mode: 0640

/etc/origin/master/policy.json
owner: root,
group: root,
mode: 0644 desired mode: 0640

**Comment by IshentRas** [comment]
Fixed by https://github.com/IshentRas/cookbook-openshift3/commit/2b566abd324e71f776e1754cc2de3a091bd04994
