### ISSUE TITLE
No default openshift_master_admission_plugin_config for OSE v3.10?

### ISSUE THREAD

**Issue by jperville** [IshentRas/cookbook-openshift3#282]
Investigating how admission plugin configs work, I found this in the code: https://github.com/IshentRas/cookbook-openshift3/blob/master/providers/openshift_create_master.rb#L43-L50

Is it normal that the `admission_default` variable is undefined when ose major version is 3.10?

**Comment by IshentRas** [comment]
It is defined but not at the same location
https://github.com/IshentRas/cookbook-openshift3/blob/master/providers/openshift_create_master.rb#L139

**Comment by jperville** [comment]
Thanks @IshentRas , I forgot that there are 2 implementations of the resource (standard and ng).
