### ISSUE TITLE
'property' not supported in our version of Chef

### ISSUE THREAD

**Issue by ianmiell** [IshentRas/cookbook-openshift3#47]
We are running 12.4.1 chef-client, which does not support property. Is it possible (for you or me) to work around the requirement to use property?

As you know, we don't control the version of Chef we use :)

**Comment by IshentRas** [comment]
Of course can you be more specific? Which part does not work for you?

**Comment by IshentRas** [comment]
Oh, leave it lol I know what you are talking about. I believe we should put it in a way convenient for everybody, therefore, I'll fix it. Anyway it was not elegant to have some bits old style and other bits new style so I shall unify all of them to old style for now

**Comment by IshentRas** [comment]
Everything has now been fixed: https://github.com/IshentRas/cookbook-openshift3/releases/tag/v1.10.29
We are now backwards compatible :+1:

**Comment by ianmiell** [comment]
👍
