### ISSUE TITLE
Chef client version 12.4

### ISSUE THREAD

**Issue by ianmiell** [IshentRas/cookbook-openshift3#49]
We have an issue at the moment where we can't build due to having an older version of chef client (12.4).

This means we can't upgrade to the latest iptables package (3.x.x) to allow this line to be run:

https://github.com/IshentRas/cookbook-openshift3/blob/827d517a0c0793ab3718b61dcbe8223fabc3aa63/recipes/common.rb#L11

our version of iptables (1.0.0) expects 'content' instead of 'lines' here.

Unfortunately an upgrade is not likely soon because a plan needs to be made for cookbooks that are not back-compatible.

I'm not sure if there is a way to run different code based on the client version in chef. A quick search seemed to suggest this was not 'the chef way'.

Do you have a strong view on this Will? One option might be to pin iptables to 1.0.0 rather than >= 1.0.0 but this may not be what you want.

**Comment by ianmiell** [comment]
Maybe this helps...

http://stackoverflow.com/questions/22833743/extract-cookbook-name-and-version-during-chef-client-run

I will investigate.

**Comment by ianmiell** [comment]
OK, I have repro'd (with ShutIt of course):

https://github.com/ianmiell/shutit-openshift-cluster/commit/ffff7a1141f909fbc2fe6c89c7536b3b6c7d38a3

and then shown that the error can be 'avoided' with, eg:

```
log run_context.cookbook_collection['iptables'].version
if run_context.cookbook_collection['iptables'].version == '3.0.0'
  iptables_rule 'firewall_jump_rule' do
    lines '-A INPUT -j OS_FIREWALL_ALLOW'
  end
end
```

so do you have any advice on how to implement (eg with template or some other method?) for the pre-3.0.0 version, before I write a PR?

**Comment by IshentRas** [comment]
@ianmiell I personally do not have any preferences about how to implement it. Just make a condition on the version..?

**Comment by ianmiell** [comment]
OKIDOKE!

**Comment by ianmiell** [comment]
Resolved.
