### ISSUE TITLE
Collaboration

### ISSUE THREAD

**Issue by IshentRas** [IshentRas/cookbook-openshift3#69]
Hi @jperville  @ianmiell 
I have added you as collaborators at chef supermarket :+1: 
Therefore, you should also be able to push new versions.

Guide for collaboration : CONTRIBUTING (Nothing special)
Feel free to amend...

**Comment by IshentRas** [comment]
https://raw.githubusercontent.com/IshentRas/cookbook-openshift3/master/CONTRIBUTING

**Comment by jperville** [comment]
Thank you very much @IshentRas :)

**Comment by ianmiell** [comment]
Thanks @IshentRas - have added kitchen testing as a step 3.
