### ISSUE TITLE
oc create secret fails in 1.2

### ISSUE THREAD

**Issue by ianmiell** [IshentRas/cookbook-openshift3#76]
`ESC[0m[2017-02-13T08:25:11+00:00] INFO: Running queued delayed notifications before re-raising exception
[2017-02-13T08:25:11+00:00] ERROR: Running exception handlers
[2017-02-13T08:25:11+00:00] ERROR: Exception handlers complete
[2017-02-13T08:25:11+00:00] FATAL: Stacktrace dumped to /root/chef-solo-example/cache/chef-stacktrace.out
[2017-02-13T08:25:11+00:00] ERROR: openshift_deploy_router[Deploy Router] (cookbook-openshift3::master_config_post line 127) had an error: Mixlib::ShellOut::ShellCommandFailed: execute[Create Hosted Router Certificate] (/root/chef-solo-example/cookbooks/cookbook-openshift3/providers/openshift_deploy_router.rb line 30) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of /usr/bin/oc create secret tls router-certs --cert=openshift-router.crt --key=openshift-router.key -n ${namespace_router} ----
STDOUT: 
STDERR: Error: unknown flag: --cert

Usage:
  oc create secret [options]

Available Commands:
  docker-registry Create a secret for use with a Docker registry.
  generic         Create a secret from a local file, directory or literal value.

Use "oc help <command>" for more information about a given command.
Use "oc options" for a list of global command-line options (applies to all commands).
---- End output of /usr/bin/oc create secret tls router-certs --cert=openshift-router.crt --key=openshift-router.key -n ${namespace_router} ----
Ran /usr/bin/oc create secret tls router-certs --cert=openshift-router.crt --key=openshift-router.key -n ${namespace_router} returned 1
[2017-02-13T08:25:11+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)`

does not work in 1.2

**Comment by IshentRas** [comment]
Should be fixed by https://github.com/IshentRas/cookbook-openshift3/commit/58174f9b9443fbbb7509e8a85438bb1804e58d05

**Comment by IshentRas** [comment]
@ianmiell Have you got the time to test https://github.com/IshentRas/cookbook-openshift3/commit/58174f9b9443fbbb7509e8a85438bb1804e58d05 ?

**Comment by ianmiell** [comment]
Testing:

` /space/git/shutit-openshift-cluster  ⑂ master +  $  COOKBOOK_VERSION=58174f9 ./run_tests.sh `

**Comment by jperville** [comment]
I found more OSE 1.2.x secret breakage while developing #86:

```
           execute[Link secret to metrics-deployer Service Account] (/tmp/vagrant-cache/chef/cookbooks/cookbook-openshift3/providers/openshift_deploy_metrics.rb line 30) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
           ---- Begin output of /usr/bin/oc secrets link metrics-deployer metrics-deployer -n openshift-infra --config=admin.kubeconfig ----
           STDOUT: 
           STDERR: error: unknown command "link metrics-deployer metrics-deployer"
           See 'oc secrets -h' for help and examples.
```

**Comment by IshentRas** [comment]
@jperville  I am tired of this version lol. Working on it now :+1:

**Comment by ianmiell** [comment]
LOL. Just as well; my tests have been failing all day due to lack of memory... rectifying.

**Comment by IshentRas** [comment]
Ok @jperville @ianmiell check #87

**Comment by ianmiell** [comment]
I believe this is fixed and tested.
