### ISSUE TITLE
yum 5.0.0 and selinux_policy

### ISSUE THREAD

**Issue by ianmiell** [IshentRas/cookbook-openshift3#81]
The tests caught a new issue which I thought I'd mention here.

yum 5.0.0 was released on the 13th:

https://supermarket.chef.io/cookbooks/yum

but selinux_policy requires 4.x.x

https://supermarket.chef.io/cookbooks/selinux_policy

Not sure this is our problem to solve, but it does mean the tests specify 4.x until further notice:

https://github.com/ianmiell/shutit-openshift-cluster/blob/master/run_tests.sh#L26

**Comment by IshentRas** [comment]
Shall we continue to track this? @ianmiell

**Comment by IshentRas** [comment]
Can we close now?
