### ISSUE TITLE
dns-search functionality appears not to work

### ISSUE THREAD

**Issue by ianmiell** [IshentRas/cookbook-openshift3#93]
This is my fault, and my problem to fix - am assigning to myself.

**Comment by IshentRas** [comment]
@ianmiell @jperville In addition the that point, I have just realised we were not setting the dnsIP correctly on nodes... :/
Should be the IP of the current node not the kubernetes svc (Since version 1.2+,3.2+)
Will send a PR shortly

**Comment by ianmiell** [comment]
Did you change this? If not, I can just remove my code as a first step (as it just doesn't work...)

**Comment by IshentRas** [comment]
Yes it has been fixed by commit 5793e7bf516943ec6ab6d651952b02deeb60740e
